import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Hobby India' message='A 2-dimensional website builder.' />
      {/* <Slider slides={SliderData} /> */}
      <Instagram />
    </div>
  );
}
